/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OGklvkGjCJY
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import {
  CollapsibleTrigger,
  CollapsibleContent,
  Collapsible,
} from "@/components/ui/collapsible"
import { SheetContent, Sheet } from "@/components/ui/sheet"

export default function Layout_v3() {
  return (
    <section className="min-h-screen flex flex-col gap-2 bg-pink-200">
      <header className="flex items-center justify-between px-4 py-2 border-b dark:border-zinc-800 bg-yellow-200">
        <Link href="#">
          <svg
            className=" h-6 w-6"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
          </svg>
          <span className="sr-only">FTP Service</span>
        </Link>
        <Link
          className="text-sm font-medium text-zinc-900 hover:text-zinc-700 dark:text-zinc-50 dark:hover:text-zinc-200"
          href="#"
        >
          FAQ
        </Link>
      </header>
      <Collapsible defaultOpen className="flex-grow flex overflow-auto min-h-full">
        <CollapsibleContent className="w-64 flex-shrink-0 border-r dark:border-zinc-800 bg-green-200 lg:open">
          <CollapsibleTrigger asChild>
            <Button
              className="w-full h-10 flex items-center justify-between px-4"
              size="icon"
              variant="outline"
            >
              <span>History</span>
              <svg
                className="h-6 w-6"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="m18 15-6-6-6 6" />
              </svg>
            </Button>
          </CollapsibleTrigger>
          <CollapsibleContent>
            <div className="overflow-y-auto">
              <h3 className="px-4 py-2 text-sm font-semibold border-b dark:border-zinc-800">
                Dummy Title 1
              </h3>
              <p className="px-4 py-2 border-b dark:border-zinc-800">
                Dummy Data 1
              </p>
              <Sheet
                className="w-64 flex-shrink-0 border-r dark:border-zinc-800 bg-blue-200"
                side="left"
              >
                <SheetContent>
                  <div className="overflow-y-auto">
                    <h3 className="px-4 py-2 text-sm font-semibold border-b dark:border-zinc-800">
                      URL History
                    </h3>
                    <div className="px-4 py-2 border-b dark:border-zinc-800">
                      <a
                        className="text-sm text-zinc-900 hover:text-zinc-700 dark:text-zinc-50 dark:hover:text-zinc-200"
                        href="#"
                      >
                        ftp://example.com
                      </a>
                    </div>
                  </div>
                </SheetContent>
              </Sheet>
            </div>
          </CollapsibleContent>
        </CollapsibleContent>
        
        <CollapsibleTrigger className="min-h-full" asChild>
          <button
            className="w-max min-h-full flex items-center justify-between"
          >
            <svg
              className="h-6 w-6 transform -rotate-90" // Added transform rotate-90
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="m18 15-6-6-6 6" />
            </svg>
          </button>
        </CollapsibleTrigger>
        <main className="flex-grow bg-purple-200" />
      </Collapsible>
      <Collapsible defaultOpen className="border-t dark:border-zinc-800 bg-red-200">
        <CollapsibleTrigger asChild>
          <Button
            className="w-full h-10 flex items-center justify-between px-4"
            size="icon"
            variant="outline"
          >
            <span>Transfers</span>
            <svg
              className=" h-6 w-6"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="m18 15-6-6-6 6" />
            </svg>
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="overflow-y-auto">
            <h3 className="px-4 py-2 text-sm font-semibold border-b dark:border-zinc-800">
              Ongoing Transfers
            </h3>
            <div className="px-4 py-2 border-b dark:border-zinc-800">
              <p className="text-sm">
                Transfer to ftp://example.com at 1.5 MB/s
              </p>
            </div>
            <h3 className="px-4 py-2 text-sm font-semibold border-b dark:border-zinc-800">
              Previous Transfers
            </h3>
            <div className="px-4 py-2 border-b dark:border-zinc-800">
              <p className="text-sm">Transfer to ftp://example.com completed</p>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>
    </section>
  )
}
