/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OGklvkGjCJY
 */
import { Collapsible } from "@/components/ui/collapsible"
import { Header } from "@/components/header"
import { Aside } from "@/components/aside"
import { Main } from "@/components/main"
import { Footer } from "@/components/footer"

export default function Layout_v3() {
  return (
    <section className="min-h-screen flex flex-col gap-2 bg-pink-200">
      <Header />
      <Collapsible
        defaultOpen
        className="flex-grow flex overflow-auto min-h-full"
      >
        <Aside />
        <Main />
      </Collapsible>
      <Footer />
    </section>
  )
}
