/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/i0caqiAiOZb
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"
import { auth } from "@/util/auth"

export async function AddFTP() {
  const session = await auth()

  if (session && session.user) {
    // console.log("Created FTP connection for user", session.user.id)
    // let res = await setFTP(session.user.id, mockFTP)
    // console.log('res in add-ftp.tsx', res)
  }

   return (
    <Card className="w-full max-w-lg">
      <CardHeader>
        <CardTitle>Add an FTP Connection</CardTitle>
        <CardDescription>Enter the details of the FTP server you want to connect to.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="server">Server</Label>
          <Input id="server" placeholder="ftp.example.com" required type="text" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="username">Username</Label>
          <Input id="username" required type="text" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" required type="password" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="port">Port</Label>
          <Input id="port" placeholder="21" required type="number" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="secure">Secure</Label>
          <div className="flex items-center space-x-2">
            <Checkbox id="secure" name="secure" />
            <Label htmlFor="secure">Enable FTPS protocol</Label>
          </div>
        </div>
      </CardContent>
      <CardFooter className="flex justify-between">
        <div className="flex space-x-2">
          <Button variant="outline">Back</Button>
          <Button className="mr-2" variant="outline">
            Save without connecting
          </Button>
        </div>
        <Button>Connect</Button>
      </CardFooter>
    </Card>
  )
}
