/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Lz4niCeKpGf
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import type { Connection } from "@/types"

export function ConnectionItem({ connection }: { connection: Connection }) {
  // const { name, createdAt, lastAccessed, history } = connection
  const history = [{ path: "/path/to/loot" }]
  
  const latestPath = history ? history[0].path : "/path/to/loot"

  return (
    <div className="flex justify-between items-start">
      <div>
        <div className="font-medium truncate">Server 1</div>
        <div className="flex flex-col gap-2">
          <div className="text-sm text-zinc-600 dark:text-zinc-500 truncate">
            Created at: August 10, 2023
          </div>
          <div className="text-sm text-zinc-500 dark:text-zinc-400 truncate">
            Last accessed: September 10, 2023, Last connected path:
            { latestPath }
          </div>
        </div>
      </div>
      <div className="flex flex-col gap-2">
        <Button size="sm" variant="outline">
          Reconnect
        </Button>
        <Button size="sm" variant="outline">
          Reconnect at previous location
        </Button>
      </div>
    </div>
  )
}

export function Connections({ keys } : { keys: string[] }) {

  return (
    <div className="flex flex-col pt-4 text-base-content">
      <Card>
        <CardHeader>
          <CardTitle>FTP Connections</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col gap-4 py-2 border-b last:border-b-0">
            {/* <ConnectionItem connection={connections[0]} /> */}
          </div>
          <div className="flex flex-col gap-4 py-2 border-b last:border-b-0">
            <div className="flex justify-between items-start">
              <div>
                <div className="font-medium truncate">Server 2</div>
                <div className="flex flex-col gap-2">
                  <div className="text-sm text-zinc-600 dark:text-zinc-500 truncate">
                    Created at: August 8, 2023
                  </div>
                  <div className="text-sm text-zinc-500 dark:text-zinc-400 truncate">
                    Last accessed: September 8, 2023, Last connected path:
                    /path/to/loot
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <Button size="sm" variant="outline">
                  Reconnect
                </Button>
                <Button size="sm" variant="outline">
                  Reconnect at previous location
                </Button>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-4 py-2 border-b last:border-b-0">
            <div className="flex justify-between items-start">
              <div>
                <div className="font-medium truncate">Server 3</div>
                <div className="flex flex-col gap-2">
                  <div className="text-sm text-zinc-600 dark:text-zinc-500 truncate">
                    Created at: August 2, 2023
                  </div>
                  <div className="text-sm text-zinc-500 dark:text-zinc-400 truncate">
                    Last accessed: September 2, 2023, Last connected path:
                    /path/to/loot
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <Button size="sm" variant="outline" className="border-accent">
                  Reconnect
                </Button>
                <Button size="sm" variant="outline" className="border-accent">
                  Reconnect at previous location
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
